channels:
- conda-forge
dependencies:
- python=3.8.20
- pip<=24.2
- pip:
  - mlflow==2.17.2
  - astunparse==1.6.3
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - matplotlib==3.7.5
  - numpy==1.24.4
  - pandas==2.0.3
  - torch==2.4.1
  - ultralytics==8.3.75
name: mlflow-env